### PR TITLE
support raw object request

### PR DESCRIPTION
**Pull request by watsy0007**
when i execute `get_object` i want get binary data. not json data.

### CODE REVIEW

**Comment by ug0** [comment]
@watsy0007 I'm not sure this PR is necessary. You can get the binary data through the `data` key of the json response.
Or could you please explain more to me if I misunderstood it?

**Comment by watsy0007** [comment]
for example: i need to download a json file to my local machine without parsing it into an elixir struct. however, I'm currently getting an elixir struct and then encoding it into binary, which is an unnecessary step.

**Comment by ug0** [comment]
As far as I see, `Object.get_object` doesn't really fit your requirement since what you need is download the file to your local machine instead of parse its content(especially when it's a large file). I suggest you use `Object.object_url` to get the download link and just download it(this [post](https://dev.to/onpointvn/download-stream-large-file-with-hackney-in-elixir-539m) might help).

Please let me know if this solves your problem.

**Comment by watsy0007** [comment]
ok, i've got your point. thanks

**Pull request closed without merging**
