### PR TITLE
Change the put object spec to support {file, path}

### PR DESCRIPTION
**Pull request by vip30**
Currently the type is String.t(), I have no idea for how to use string to put object in oss.

That's why I change the example and the spec

Thanks

Ref: https://stackoverflow.com/questions/37855971/httpoison-upload-file

### CODE REVIEW

**Comment by ug0** [comment]
I'm not sure if it's still a problem since you closed it. When using [`PutObject`](https://help.aliyun.com/document_detail/31978.html?spm=a2c4g.11186623.2.35.4bc060e80NvhPS#reference-l5p-ftw-tdb), you should pass the file content in string. Perhaps what you actually want is [`PostObject`](https://help.aliyun.com/document_detail/31988.html?spm=a2c4g.11186623.2.43.4bc060e80NvhPS#title-o3i-svs-5ot)?

**Comment by vip30** [comment]
Yes I figure out how to use it.

But I think this approach will consume so much memory

I just thinking about how to deal with it

**Comment by ug0** [comment]
If you want to upload a large object in server side, I suggest split the object into several parts and use [`AppendObject`](https://help.aliyun.com/document_detail/31981.html?spm=a2c4g.11186623.6.1603.55f020be166Jyt).

**Comment by ug0** [comment]
@vip30 
I just released a new version which added [Multipart Upload](https://hexdocs.pm/aliyun_oss/Aliyun.Oss.Object.MultipartUpload.html#content). I hope this will help you deal with large files.

**Pull request closed without merging**
